default_platform(:ios)

# Default temporary keychain password and name, if not included from environment
TEMP_KEYCHAIN_NAME_DEFAULT = "fastlane_flutter"
TEMP_KEYCHAN_PASSWORD_DEFAULT = "temppassword"
APP_ID = ENV['FIREBASE_APPID'] || "1:924200794788:ios:45665cf64d60b47866c431"
FIREBASE_TOKEN = ENV['FIREBASE_CI_TOKEN']


# Remove the temporary keychain, if it exists
def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

# Create the temporary keychain with name and password
def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: false
  )
end

# Ensure we have a fresh, empty temporary keychain
def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  desc "Build & sign iOS app"
  lane :build_ios do |options|
    disable_automatic_code_signing(
      path: "./Runner.xcodeproj",
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      profile_name: "match AdHoc #{CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)}",
      code_sign_identity: "iPhone Distribution"
    )
    keychain_name = ENV['TEMP_KEYCHAIN_NAME'] || TEMP_KEYCHAIN_NAME_DEFAULT
    keychain_password = ENV['TEMP_KEYCHAIN_PASSWORD'] || TEMP_KEYCHAN_PASSWORD_DEFAULT
    ensure_temp_keychain(keychain_name, keychain_password)
    match(
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      type: "adhoc",
      readonly: is_ci,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      git_url: "git@gitawse1.hagerty.com:Hagerty/ios-certificates.git",
      git_branch: "updates",
      force_for_new_devices: true
    )
    increment_build_number(
      build_number: ENV["BUILD_NUMBER"]
    )
    build_ios_app(
      configuration: "Debug",
      export_options: {
          method: "ad-hoc"
      },
      output_directory: "./build/Runner"
    )

  end
  desc "Build & sign iOS app"
  lane :build_release_candidate do |options|
    disable_automatic_code_signing(
      path: "./Runner.xcodeproj",
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      profile_name: "match AppStore #{CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)}",
      code_sign_identity: "iPhone Distribution"
    )
    keychain_name = ENV['TEMP_KEYCHAIN_NAME'] || TEMP_KEYCHAIN_NAME_DEFAULT
    keychain_password = ENV['TEMP_KEYCHAIN_PASSWORD'] || TEMP_KEYCHAN_PASSWORD_DEFAULT
    ensure_temp_keychain(keychain_name, keychain_password)
    match(
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      type: "appstore",
      readonly: is_ci,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      git_url: "git@gitawse1.hagerty.com:Hagerty/ios-certificates.git",
      git_branch: "updates"
    )
    increment_build_number(
      build_number: ENV["BUILD_NUMBER"]
    )
    build_ios_app(
      export_options: {
          method: "app-store"
      },
      output_directory: "./build/Runner"
    )
    delete_temp_keychain(keychain_name)
  end

  desc "Deploy a new beta build"
  lane :distribute_beta do |options|
    # Upload to test flight or AppStore depending on caller parameters
    firebase_app_distribution(
          app: APP_ID,
          groups: "testers",
          release_notes: ENV["RELEASE_NOTES"],
          firebase_cli_token: FIREBASE_TOKEN,
          ipa_path: "./build/Runner/Runner.ipa"
      )
  end

  desc "Deploy (Upload to testflight)"
  lane :deploy_release_candidate do |options|
    # Upload to test flight or AppStore depending on caller parameters
    upload_to_testflight(
      skip_submission: true,
      ipa: "./build/Runner/Runner.ipa",
      team_id: "4J6T7JTR97",
      team_name: "THE HAGERTY GROUP INC"
    )
  end
end
# Automatically update fastlane
update_fastlane

default_platform(:ios)

# Default temporary keychain password and name, if not included from environment
TEMP_KEYCHAIN_NAME_DEFAULT = "fastlane_flutter"
TEMP_KEYCHAN_PASSWORD_DEFAULT = "temppassword"
APP_ID = ENV['FIREBASE_APPID'] || "1:924200794788:ios:45665cf64d60b47866c431"
FIREBASE_TOKEN = ENV['FIREBASE_CI_TOKEN']


# Remove the temporary keychain, if it exists
def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

# Create the temporary keychain with name and password
def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: false
  )
end

# Ensure we have a fresh, empty temporary keychain
def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  desc "Build & sign iOS app"
  lane :build_ios do |options|
    disable_automatic_code_signing(
      path: "./Runner.xcodeproj",
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      profile_name: "match AdHoc #{CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)}",
      code_sign_identity: "iPhone Distribution"
    )
    keychain_name = ENV['TEMP_KEYCHAIN_NAME'] || TEMP_KEYCHAIN_NAME_DEFAULT
    keychain_password = ENV['TEMP_KEYCHAIN_PASSWORD'] || TEMP_KEYCHAN_PASSWORD_DEFAULT
    ensure_temp_keychain(keychain_name, keychain_password)
    match(
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      type: "adhoc",
      readonly: is_ci,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      git_url: "git@gitawse1.hagerty.com:Hagerty/ios-certificates.git",
      git_branch: "updates",
      force_for_new_devices: true
    )
    increment_build_number(
      build_number: ENV["BUILD_NUMBER"]
    )
    build_ios_app(
      export_options: {
          method: "ad-hoc"
      },
      output_directory: "./build/Runner"
    )

  end
  desc "Build & sign iOS app"
  lane :build_release_candidate do |options|
    disable_automatic_code_signing(
      path: "./Runner.xcodeproj",
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      profile_name: "match AppStore #{CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)}",
      code_sign_identity: "iPhone Distribution"
    )
    keychain_name = ENV['TEMP_KEYCHAIN_NAME'] || TEMP_KEYCHAIN_NAME_DEFAULT
    keychain_password = ENV['TEMP_KEYCHAIN_PASSWORD'] || TEMP_KEYCHAN_PASSWORD_DEFAULT
    ensure_temp_keychain(keychain_name, keychain_password)
    match(
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      type: "appstore",
      readonly: is_ci,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      git_url: "git@gitawse1.hagerty.com:Hagerty/ios-certificates.git",
      git_branch: "updates"
    )
    increment_build_number(
      build_number: ENV["BUILD_NUMBER"]
    )
    build_ios_app(
      export_options: {
          method: "app-store"
      },
      output_directory: "./build/Runner"
    )
    delete_temp_keychain(keychain_name)
  end

  desc "Deploy a new beta build"
  lane :distribute_beta do |options|
    # Upload to test flight or AppStore depending on caller parameters
    firebase_app_distribution(
          app: APP_ID,
          groups: "testers",
          release_notes: ENV["RELEASE_NOTES"],
          firebase_cli_token: FIREBASE_TOKEN,
          ipa_path: "./build/Runner/Runner.ipa"
      )
  end

  desc "Deploy (Upload to testflight)"
  lane :deploy_release_candidate do |options|
    # Upload to test flight or AppStore depending on caller parameters
    upload_to_testflight(
      skip_submission: true,
      ipa: "./build/Runner/Runner.ipa",
      team_id: "4J6T7JTR97",
      team_name: "THE HAGERTY GROUP INC"
    )
  end
end
